# Raster Validation

Validates raster built-up datasets (TEMPO, GHSL Built-S/V/H, Google OBT) against reference building footprints.

Pipeline per city:
1. Tile the AOI into 1 km × 1 km cells
2. For each enabled raster candidate, read the year-specific file (`{city_slug}_{name}_{year}.tif`)
3. Rasterize reference footprints onto the candidate grid (fractional coverage via oversampling)
4. Compute tile-level binary (TP/FP/FN/F1) and area-based metrics
5. Save tile metrics, city summary, and figures to `outputs/`

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import os
import sys
os.chdir("/content/drive/MyDrive/Gates Foundation/Building Dataset Validation/")

In [3]:
from pathlib import Path

PROJECT_ROOT = Path("/content/drive/MyDrive/Gates Foundation/Building Dataset Validation")
CONFIG_PATH  = PROJECT_ROOT / "configs/validation_configs.yaml"

# Set overwrite=True to re-run cities whose raster outputs already exist.
# When False (default), cities with an existing sentinel parquet are skipped automatically.
OVERWRITE = True

In [4]:
os.chdir(PROJECT_ROOT)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [5]:
# import rasterio
# from pathlib import Path

# tile_path = Path(f"{PROJECT_ROOT}/data/WSFsoftRelease/Oceania/WSFtracker_20160701-20250701_-126_-26.tif")

# with rasterio.open(tile_path) as src:
#     print("CRS:", src.crs)
#     print("Bounds:", src.bounds)
#     print("Shape:", (src.height, src.width))
#     print("Resolution:", src.res)

In [6]:
# from glob import glob

# paths = glob(f"{PROJECT_ROOT}/data/WSFsoftRelease/**/*.tif", recursive=True)[:5]

# for p in paths:
#     with rasterio.open(p) as src:
#         print(p.split("/")[-1], "->", src.bounds)

In [7]:
import logging
import yaml
from src.validator import UrbanValidator

for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
    force=True,
)

with open(CONFIG_PATH) as f:
    _cfg_preview = yaml.safe_load(f)

raster_datasets = _cfg_preview.get("raster", {}).get("datasets", [])
enabled = [
    f"{d['name']}" + (f"_{d['year']}" if d.get("year") is not None else "")
    for d in raster_datasets
    if d.get("enabled", True)
]
print(f"Config: {CONFIG_PATH}")
print(f"Enabled raster datasets: {enabled}")

Config: /content/drive/MyDrive/Gates Foundation/Building Dataset Validation/configs/validation_configs.yaml
Enabled raster datasets: ['obt_2023', 'tempo_2023q4', 'ghsl_built_s_2025', 'wsf_tracker']

In [8]:
# Patch overwrite flag and instantiate the Validator.
# This reads the config and AOI tracker, resolves file paths,
# and logs how many city datasets are queued.
import tempfile

with open(CONFIG_PATH) as f:
    _cfg_patched = yaml.safe_load(f)
_cfg_patched.setdefault("output", {})["overwrite"] = OVERWRITE

_tmp = tempfile.NamedTemporaryFile(
    mode="w", suffix=".yaml", delete=False, dir=PROJECT_ROOT / "configs"
)
yaml.dump(_cfg_patched, _tmp)
_tmp.close()
_PATCHED_CONFIG_PATH = _tmp.name

v = UrbanValidator(_PATCHED_CONFIG_PATH)
print(f"\nCities queued: {len(v.datasets)}")
for ds in v.datasets:
    print(f"  {ds['id']}")

20:40:35  INFO      Validation tracker: 52 -> 52 suitable rows.
20:40:36  INFO      Loaded 52 dataset(s) for validation.
20:40:36  INFO      Loaded 52 dataset(s) for validation.

Cities queued: 52
  usa-brentwood
  usa-sandiego
  usa-boise
  usa-lasvegas
  usa-saltlakecity
  usa-permianbasin
  mex-mexicocity
  usa-bentonville
  usa-gonzales
  usa-atlanta
  usa-portstlucie
  pan-panamacity
  usa-raleigh
  jam-kingston
  usa-allentown
  per-cusco
  chl-calama
  bra-manaus
  bra-saopaulo
  sen-dakar
  alg-tindouf
  gha-kumasi
  lby-benghazi
  zmb-lusaka
  zaf-durban
  egy-cairo
  sdn-khartoum
  uga-kampala
  gbr-birmingham
  gbr-london
  nld-rotterdam
  rou-bucharest
  yem-dhamar
  sau-riyadh
  kwt-kuwaitcity
  rus-astrakhan
  are-abudhabi
  uzb-zarafshan
  ind-mumbai
  ind-tada
  ind-vijayawada
  bgd-dhaka
  chn-chengdu
  chn-zhuhai
  chn-guangzhou
  chn-wuhan
  chn-lujiang
  chn-yangzhou
  phl-angelescity
  chn-shanghai
  kor-sejong
  aus-melbourne

In [9]:
# Preview: show which raster files will be looked up for each city × dataset combination.
# Files that don't exist on disk are flagged so you can fix paths before running.
import pandas as pd
from pathlib import Path

data_dir = Path(_cfg_patched.get("root_dir", str(PROJECT_ROOT))) / _cfg_patched.get("data_dir", "data/01_raw")

preview_rows = []
for ds in v.datasets:
    city_slug    = ds["id"].lower()
    city_slug_us = city_slug.replace("-", "_")
    rast_dir     = data_dir / ds["id"] / "raster"

    for cand in _cfg_patched.get("raster", {}).get("datasets", []):
        if not cand.get("enabled", True):
            continue
        ds_name = cand["name"].replace("-", "_")
        year    = cand.get("year")
        if year is not None:
            fpath = rast_dir / f"{city_slug_us}_{ds_name}_{year}.tif"
        else:
            matches = sorted(rast_dir.glob(f"{city_slug_us}_{ds_name}*.tif"))
            fpath   = matches[0] if matches else rast_dir / f"{city_slug_us}_{ds_name}_?.tif"
        preview_rows.append({
            "city":    ds["id"],
            "dataset": f"{ds_name}_{year}" if year is not None else ds_name,
            "file":    fpath.name,
            "exists":  fpath.exists(),
        })

preview_df = pd.DataFrame(preview_rows)
missing = preview_df[~preview_df["exists"]]
print(f"Total city × dataset pairs: {len(preview_df)}")
print(f"Missing files:              {len(missing)}")
display(preview_df)

Total city × dataset pairs: 208
Missing files:              27

,city,dataset,file,exists
0,usa-brentwood,obt_2023,usa_brentwood_obt_2023.tif,False
1,usa-brentwood,tempo_2023q4,usa_brentwood_tempo_2023q4.tif,True
2,usa-brentwood,ghsl_built_s_2025,usa_brentwood_ghsl_built_s_2025.tif,True
3,usa-brentwood,wsf_tracker,usa_brentwood_wsf_tracker.tif,True
4,usa-sandiego,obt_2023,usa_sandiego_obt_2023.tif,True
...,...,...,...,...
203,kor-sejong,wsf_tracker,kor_sejong_wsf_tracker.tif,True
204,aus-melbourne,obt_2023,aus_melbourne_obt_2023.tif,False
205,aus-melbourne,tempo_2023q4,aus_melbourne_tempo_2023q4.tif,True
206,aus-melbourne,ghsl_built_s_2025,aus_melbourne_ghsl_built_s_2025.tif,True
207,aus-melbourne,wsf_tracker,aus_melbourne_wsf_tracker.tif,True

In [10]:
preview_df

,city,dataset,file,exists
0,usa-brentwood,obt_2023,usa_brentwood_obt_2023.tif,False
1,usa-brentwood,tempo_2023q4,usa_brentwood_tempo_2023q4.tif,True
2,usa-brentwood,ghsl_built_s_2025,usa_brentwood_ghsl_built_s_2025.tif,True
3,usa-brentwood,wsf_tracker,usa_brentwood_wsf_tracker.tif,True
4,usa-sandiego,obt_2023,usa_sandiego_obt_2023.tif,True
...,...,...,...,...
203,kor-sejong,wsf_tracker,kor_sejong_wsf_tracker.tif,True
204,aus-melbourne,obt_2023,aus_melbourne_obt_2023.tif,False
205,aus-melbourne,tempo_2023q4,aus_melbourne_tempo_2023q4.tif,True
206,aus-melbourne,ghsl_built_s_2025,aus_melbourne_ghsl_built_s_2025.tif,True
207,aus-melbourne,wsf_tracker,aus_melbourne_wsf_tracker.tif,True

In [11]:
results = v.validate_raster()

# Clean up temp config
try:
    os.unlink(_PATCHED_CONFIG_PATH)
except Exception:
    pass

# Summary
summary = pd.DataFrame(
    [{"city": k, "status": "ok" if ok else "failed"} for k, ok in results.items()]
)
print(f"\nDone — {len(summary)} cities processed.\n")
display(summary.groupby("status")["city"].count().rename("count").to_frame())
display(summary)

20:40:36  INFO      ━━━━  usa-brentwood (raster)  ━━━━
20:40:36  INFO      MEM [usa-brentwood raster start] RSS = 305 MB
20:40:37  INFO      [usa-brentwood] Raster CRS: EPSG:32610 | 16 tiles.
20:40:37  INFO      [usa-brentwood] Raster reference buildings: 2107 (from 1 file(s))
20:40:37  WARNING   [usa-brentwood / obt] No raster file found (pattern: usa_brentwood_obt_2023*).
20:40:37  INFO      [usa-brentwood / tempo_2023q4] Raster candidate: usa_brentwood_tempo_2023q4.tif
20:40:37  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:40:37  INFO      [usa-brentwood / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:40:37  INFO      MEM [usa-brentwood/tempo_2023q4 raster done] RSS = 334 MB
20:40:37  INFO      [usa-brentwood / ghsl_built_s_2025] Raster candidate: usa_brentwood_ghsl_built_s_2025.tif
20:40:37  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:40:38  INFO      [usa-brentwood / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:40:38  INFO      MEM [usa-brentwood/ghsl_built_s_2025 raster done] RSS = 334 MB
20:40:38  INFO      [usa-brentwood / wsf_tracker] Raster candidate: usa_brentwood_wsf_tracker.tif
20:40:39  INFO      [usa-brentwood / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:40:39  INFO      MEM [usa-brentwood/wsf_tracker raster done] RSS = 347 MB
20:40:39  INFO      [usa-brentwood] Raster city summary saved.
20:40:42  INFO      MEM [usa-brentwood raster end] RSS = 362 MB
20:40:42  INFO      [usa-brentwood] ✓ Raster complete.
20:40:42  INFO      ━━━━  usa-sandiego (raster)  ━━━━
20:40:42  INFO      MEM [usa-sandiego raster start] RSS = 362 MB
20:40:42  INFO      [usa-sandiego] Raster CRS: EPSG:32611 | 50 tiles.
20:40:43  INFO      [usa-sandiego] Raster reference buildings: 9706 (from 1 file(s))
20:40:43  INFO      [usa-sandiego / obt_2023] Raster candidate: usa_sandiego_obt_2023.tif
20:40:43  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:43  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:45  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:46  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:46  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:46  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:47  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:48  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:49  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:49  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:49  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:49  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:49  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:49  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:49  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:49  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:50  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:50  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:50  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:50  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:50  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:51  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:52  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:52  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:52  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:40:55  INFO      [usa-sandiego / obt_2023] Raster tile metrics saved → raster_metrics_tiles_obt_2023.parquet
20:40:55  INFO      MEM [usa-sandiego/obt_2023 raster done] RSS = 575 MB
20:40:55  INFO      [usa-sandiego / tempo_2023q4] Raster candidate: usa_sandiego_tempo_2023q4.tif
20:40:55  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:40:57  INFO      [usa-sandiego / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:40:57  INFO      MEM [usa-sandiego/tempo_2023q4 raster done] RSS = 575 MB
20:40:57  INFO      [usa-sandiego / ghsl_built_s_2025] Raster candidate: usa_sandiego_ghsl_built_s_2025.tif
20:40:57  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:40:58  INFO      [usa-sandiego / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:40:58  INFO      MEM [usa-sandiego/ghsl_built_s_2025 raster done] RSS = 575 MB
20:40:58  INFO      [usa-sandiego / wsf_tracker] Raster candidate: usa_sandiego_wsf_tracker.tif
20:41:03  INFO      [usa-sandiego / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:41:03  INFO      MEM [usa-sandiego/wsf_tracker raster done] RSS = 576 MB
20:41:03  INFO      [usa-sandiego] Raster city summary saved.
20:41:07  INFO      MEM [usa-sandiego raster end] RSS = 560 MB
20:41:07  INFO      [usa-sandiego] ✓ Raster complete.
20:41:07  INFO      ━━━━  usa-boise (raster)  ━━━━
20:41:07  INFO      MEM [usa-boise raster start] RSS = 560 MB
20:41:07  INFO      [usa-boise] Raster CRS: EPSG:32611 | 16 tiles.
20:41:07  INFO      [usa-boise] Raster reference buildings: 4723 (from 1 file(s))
20:41:07  WARNING   [usa-boise / obt] No raster file found (pattern: usa_boise_obt_2023*).
20:41:07  INFO      [usa-boise / tempo_2023q4] Raster candidate: usa_boise_tempo_2023q4.tif
20:41:07  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:41:08  INFO      [usa-boise / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:41:08  INFO      MEM [usa-boise/tempo_2023q4 raster done] RSS = 560 MB
20:41:08  INFO      [usa-boise / ghsl_built_s_2025] Raster candidate: usa_boise_ghsl_built_s_2025.tif
20:41:08  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:41:08  INFO      [usa-boise / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:41:08  INFO      MEM [usa-boise/ghsl_built_s_2025 raster done] RSS = 560 MB
20:41:08  INFO      [usa-boise / wsf_tracker] Raster candidate: usa_boise_wsf_tracker.tif
20:41:10  INFO      [usa-boise / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:41:10  INFO      MEM [usa-boise/wsf_tracker raster done] RSS = 570 MB
20:41:10  INFO      [usa-boise] Raster city summary saved.
20:41:13  INFO      MEM [usa-boise raster end] RSS = 561 MB
20:41:13  INFO      [usa-boise] ✓ Raster complete.
20:41:13  INFO      ━━━━  usa-lasvegas (raster)  ━━━━

[zaf-durban_SN7.geojson] fixing 16 invalid geometries...

20:44:52  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:53  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:54  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:44:56  INFO      [zaf-durban / obt_2023] Raster tile metrics saved → raster_metrics_tiles_obt_2023.parquet
20:44:56  INFO      MEM [zaf-durban/obt_2023 raster done] RSS = 562 MB
20:44:56  INFO      [zaf-durban / tempo_2023q4] Raster candidate: zaf_durban_tempo_2023q4.tif
20:44:56  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:44:57  INFO      [zaf-durban / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:44:57  INFO      MEM [zaf-durban/tempo_2023q4 raster done] RSS = 562 MB
20:44:57  INFO      [zaf-durban / ghsl_built_s_2025] Raster candidate: zaf_durban_ghsl_built_s_2025.tif
20:44:57  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:44:59  INFO      [zaf-durban / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:44:59  INFO      MEM [zaf-durban/ghsl_built_s_2025 raster done] RSS = 562 MB
20:44:59  INFO      [zaf-durban / wsf_tracker] Raster candidate: zaf_durban_wsf_tracker.tif
20:45:01  INFO      [zaf-durban / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:45:01  INFO      MEM [zaf-durban/wsf_tracker raster done] RSS = 572 MB
20:45:02  INFO      [zaf-durban] Raster city summary saved.
20:45:06  INFO      MEM [zaf-durban raster end] RSS = 562 MB
20:45:06  INFO      [zaf-durban] ✓ Raster complete.
20:45:06  INFO      ━━━━  egy-cairo (raster)  ━━━━
20:45:06  INFO      MEM [egy-cairo raster start] RSS = 562 MB
20:45:06  INFO      [egy-cairo] Raster CRS: EPSG:32636 | 75 tiles.
20:45:06  INFO      [egy-cairo] Raster reference buildings: 3717 (from 1 file(s))
20:45:06  INFO      [egy-cairo / obt_2023] Raster candidate: egy_cairo_obt_2023.tif
20:45:06  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:06  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.

[egy-cairo_SN7.geojson] fixing 1 invalid geometries...

20:45:06  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:06  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:07  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:08  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:09  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:10  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:10  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:10  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:10  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:10  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:11  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:11  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:11  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:11  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:11  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:11  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:11  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:11  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:12  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:13  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:45:14  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.

[chn-chengdu_SN7.geojson] fixing 1 invalid geometries...

20:48:05  INFO      [chn-chengdu / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:48:05  INFO      MEM [chn-chengdu/tempo_2023q4 raster done] RSS = 732 MB
20:48:05  INFO      [chn-chengdu / ghsl_built_s_2025] Raster candidate: chn_chengdu_ghsl_built_s_2025.tif
20:48:05  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:07  INFO      [chn-chengdu / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:48:07  INFO      MEM [chn-chengdu/ghsl_built_s_2025 raster done] RSS = 732 MB
20:48:07  INFO      [chn-chengdu / wsf_tracker] Raster candidate: chn_chengdu_wsf_tracker.tif
20:48:13  INFO      [chn-chengdu / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:48:13  INFO      MEM [chn-chengdu/wsf_tracker raster done] RSS = 732 MB
20:48:13  INFO      [chn-chengdu] Raster city summary saved.
20:48:16  INFO      MEM [chn-chengdu raster end] RSS = 726 MB
20:48:16  INFO      [chn-chengdu] ✓ Raster complete.
20:48:16  INFO      ━━━━  chn-zhuhai (raster)  ━━━━
20:48:16  INFO      MEM [chn-zhuhai raster start] RSS = 726 MB
20:48:16  INFO      [chn-zhuhai] Raster CRS: EPSG:32649 | 25 tiles.
20:48:16  INFO      [chn-zhuhai] Raster reference buildings: 1218 (from 1 file(s))
20:48:16  WARNING   [chn-zhuhai / obt] No raster file found (pattern: chn_zhuhai_obt_2023*).
20:48:16  INFO      [chn-zhuhai / tempo_2023q4] Raster candidate: chn_zhuhai_tempo_2023q4.tif
20:48:16  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:17  INFO      [chn-zhuhai / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:48:17  INFO      MEM [chn-zhuhai/tempo_2023q4 raster done] RSS = 726 MB
20:48:17  INFO      [chn-zhuhai / ghsl_built_s_2025] Raster candidate: chn_zhuhai_ghsl_built_s_2025.tif
20:48:17  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:17  INFO      [chn-zhuhai / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:48:17  INFO      MEM [chn-zhuhai/ghsl_built_s_2025 raster done] RSS = 726 MB
20:48:17  INFO      [chn-zhuhai / wsf_tracker] Raster candidate: chn_zhuhai_wsf_tracker.tif
20:48:19  INFO      [chn-zhuhai / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:48:19  INFO      MEM [chn-zhuhai/wsf_tracker raster done] RSS = 726 MB
20:48:19  INFO      [chn-zhuhai] Raster city summary saved.
20:48:22  INFO      MEM [chn-zhuhai raster end] RSS = 733 MB
20:48:22  INFO      [chn-zhuhai] ✓ Raster complete.
20:48:22  INFO      ━━━━  chn-guangzhou (raster)  ━━━━
20:48:22  INFO      MEM [chn-guangzhou raster start] RSS = 733 MB
20:48:22  INFO      [chn-guangzhou] Raster CRS: EPSG:32649 | 54 tiles.
20:48:23  INFO      [chn-guangzhou] Raster reference buildings: 8235 (from 1 file(s))
20:48:23  WARNING   [chn-guangzhou / obt] No raster file found (pattern: chn_guangzhou_obt_2023*).
20:48:23  INFO      [chn-guangzhou / tempo_2023q4] Raster candidate: chn_guangzhou_tempo_2023q4.tif
20:48:23  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:24  INFO      [chn-guangzhou / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:48:24  INFO      MEM [chn-guangzhou/tempo_2023q4 raster done] RSS = 733 MB
20:48:24  INFO      [chn-guangzhou / ghsl_built_s_2025] Raster candidate: chn_guangzhou_ghsl_built_s_2025.tif
20:48:24  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:26  INFO      [chn-guangzhou / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:48:26  INFO      MEM [chn-guangzhou/ghsl_built_s_2025 raster done] RSS = 733 MB
20:48:26  INFO      [chn-guangzhou / wsf_tracker] Raster candidate: chn_guangzhou_wsf_tracker.tif
20:48:29  INFO      [chn-guangzhou / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:48:29  INFO      MEM [chn-guangzhou/wsf_tracker raster done] RSS = 733 MB
20:48:29  INFO      [chn-guangzhou] Raster city summary saved.
20:48:32  INFO      MEM [chn-guangzhou raster end] RSS = 726 MB
20:48:32  INFO      [chn-guangzhou] ✓ Raster complete.
20:48:32  INFO      ━━━━  chn-wuhan (raster)  ━━━━
20:48:32  INFO      MEM [chn-wuhan raster start] RSS = 726 MB
20:48:32  INFO      [chn-wuhan] Raster CRS: EPSG:32650 | 25 tiles.
20:48:33  INFO      [chn-wuhan] Raster reference buildings: 1793 (from 1 file(s))
20:48:33  WARNING   [chn-wuhan / obt] No raster file found (pattern: chn_wuhan_obt_2023*).
20:48:33  INFO      [chn-wuhan / tempo_2023q4] Raster candidate: chn_wuhan_tempo_2023q4.tif
20:48:33  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:33  INFO      [chn-wuhan / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:48:33  INFO      MEM [chn-wuhan/tempo_2023q4 raster done] RSS = 726 MB
20:48:33  INFO      [chn-wuhan / ghsl_built_s_2025] Raster candidate: chn_wuhan_ghsl_built_s_2025.tif
20:48:33  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:34  INFO      [chn-wuhan / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:48:34  INFO      MEM [chn-wuhan/ghsl_built_s_2025 raster done] RSS = 726 MB
20:48:34  INFO      [chn-wuhan / wsf_tracker] Raster candidate: chn_wuhan_wsf_tracker.tif
20:48:35  INFO      [chn-wuhan / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:48:35  INFO      MEM [chn-wuhan/wsf_tracker raster done] RSS = 726 MB
20:48:35  INFO      [chn-wuhan] Raster city summary saved.
20:48:38  INFO      MEM [chn-wuhan raster end] RSS = 735 MB
20:48:38  INFO      [chn-wuhan] ✓ Raster complete.
20:48:38  INFO      ━━━━  chn-lujiang (raster)  ━━━━
20:48:38  INFO      MEM [chn-lujiang raster start] RSS = 735 MB
20:48:38  INFO      [chn-lujiang] Raster CRS: EPSG:32650 | 49 tiles.
20:48:38  INFO      [chn-lujiang] Raster reference buildings: 4909 (from 1 file(s))
20:48:38  WARNING   [chn-lujiang / obt] No raster file found (pattern: chn_lujiang_obt_2023*).
20:48:38  INFO      [chn-lujiang / tempo_2023q4] Raster candidate: chn_lujiang_tempo_2023q4.tif
20:48:38  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:40  INFO      [chn-lujiang / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:48:40  INFO      MEM [chn-lujiang/tempo_2023q4 raster done] RSS = 735 MB
20:48:40  INFO      [chn-lujiang / ghsl_built_s_2025] Raster candidate: chn_lujiang_ghsl_built_s_2025.tif
20:48:40  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:41  INFO      [chn-lujiang / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:48:41  INFO      MEM [chn-lujiang/ghsl_built_s_2025 raster done] RSS = 735 MB
20:48:41  INFO      [chn-lujiang / wsf_tracker] Raster candidate: chn_lujiang_wsf_tracker.tif
20:48:44  INFO      [chn-lujiang / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:48:44  INFO      MEM [chn-lujiang/wsf_tracker raster done] RSS = 735 MB
20:48:44  INFO      [chn-lujiang] Raster city summary saved.
20:48:47  INFO      MEM [chn-lujiang raster end] RSS = 735 MB
20:48:47  INFO      [chn-lujiang] ✓ Raster complete.
20:48:47  INFO      ━━━━  chn-yangzhou (raster)  ━━━━
20:48:47  INFO      MEM [chn-yangzhou raster start] RSS = 735 MB
20:48:47  INFO      [chn-yangzhou] Raster CRS: EPSG:32650 | 25 tiles.
20:48:47  INFO      [chn-yangzhou] Raster reference buildings: 5719 (from 1 file(s))
20:48:47  WARNING   [chn-yangzhou / obt] No raster file found (pattern: chn_yangzhou_obt_2023*).
20:48:47  INFO      [chn-yangzhou / tempo_2023q4] Raster candidate: chn_yangzhou_tempo_2023q4.tif
20:48:47  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:48  INFO      [chn-yangzhou / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:48:48  INFO      MEM [chn-yangzhou/tempo_2023q4 raster done] RSS = 735 MB
20:48:48  INFO      [chn-yangzhou / ghsl_built_s_2025] Raster candidate: chn_yangzhou_ghsl_built_s_2025.tif
20:48:48  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:49  INFO      [chn-yangzhou / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:48:49  INFO      MEM [chn-yangzhou/ghsl_built_s_2025 raster done] RSS = 735 MB
20:48:49  INFO      [chn-yangzhou / wsf_tracker] Raster candidate: chn_yangzhou_wsf_tracker.tif
20:48:51  INFO      [chn-yangzhou / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:48:51  INFO      MEM [chn-yangzhou/wsf_tracker raster done] RSS = 735 MB
20:48:51  INFO      [chn-yangzhou] Raster city summary saved.
20:48:54  INFO      MEM [chn-yangzhou raster end] RSS = 735 MB
20:48:54  INFO      [chn-yangzhou] ✓ Raster complete.
20:48:54  INFO      ━━━━  phl-angelescity (raster)  ━━━━
20:48:54  INFO      MEM [phl-angelescity raster start] RSS = 735 MB
20:48:55  INFO      [phl-angelescity] Raster CRS: EPSG:32651 | 25 tiles.
20:48:55  INFO      [phl-angelescity] Raster reference buildings: 7600 (from 1 file(s))
20:48:55  INFO      [phl-angelescity / obt_2023] Raster candidate: phl_angelescity_obt_2023.tif
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:55  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:56  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:57  WARNING   CPLE_AppDefined:Value 0 in the source dataset has been changed to 1.4013e-45 in the destination dataset to avoid being treated as NoData. To avoid this, select a different NoData value for the destination dataset.
20:48:58  INFO      [phl-angelescity / obt_2023] Raster tile metrics saved → raster_metrics_tiles_obt_2023.parquet
20:48:58  INFO      MEM [phl-angelescity/obt_2023 raster done] RSS = 735 MB
20:48:58  INFO      [phl-angelescity / tempo_2023q4] Raster candidate: phl_angelescity_tempo_2023q4.tif
20:48:58  WARNING   [native-resolution guard] dataset='tempo' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:48:59  INFO      [phl-angelescity / tempo_2023q4] Raster tile metrics saved → raster_metrics_tiles_tempo_2023q4.parquet
20:48:59  INFO      MEM [phl-angelescity/tempo_2023q4 raster done] RSS = 735 MB
20:48:59  INFO      [phl-angelescity / ghsl_built_s_2025] Raster candidate: phl_angelescity_ghsl_built_s_2025.tif
20:48:59  WARNING   [native-resolution guard] dataset='ghsl_built_s' native_resolution_m=100.0, tolerance_factor=0.95, minimum_allowed_eval_resolution=95.000 m. Blocked finer evaluation grid(s): 10m (10.0 m) | Skipping blocked grid(s).
20:49:00  INFO      [phl-angelescity / ghsl_built_s_2025] Raster tile metrics saved → raster_metrics_tiles_ghsl_built_s_2025.parquet
20:49:00  INFO      MEM [phl-angelescity/ghsl_built_s_2025 raster done] RSS = 735 MB
20:49:00  INFO      [phl-angelescity / wsf_tracker] Raster candidate: phl_angelescity_wsf_tracker.tif
20:49:02  INFO      [phl-angelescity / wsf_tracker] Raster tile metrics saved → raster_metrics_tiles_wsf_tracker.parquet
20:49:02  INFO      MEM [phl-angelescity/wsf_tracker raster done] RSS = 735 MB
20:49:03  INFO      [phl-angelescity] Raster city summary saved.
20:49:07  INFO      MEM [phl-angelescity raster end] RSS = 733 MB
20:49:07  INFO      [phl-angelescity] ✓ Raster complete.
20:49:07  INFO      ━━━━  chn-shanghai (raster)  ━━━━

Done — 52 cities processed.

        count
status
ok         52

                city status
0      usa-brentwood     ok
1       usa-sandiego     ok
2          usa-boise     ok
3       usa-lasvegas     ok
4   usa-saltlakecity     ok
5   usa-permianbasin     ok
6     mex-mexicocity     ok
7    usa-bentonville     ok
8       usa-gonzales     ok
9        usa-atlanta     ok
10   usa-portstlucie     ok
11    pan-panamacity     ok
12       usa-raleigh     ok
13      jam-kingston     ok
14     usa-allentown     ok
15         per-cusco     ok
16        chl-calama     ok
17        bra-manaus     ok
18      bra-saopaulo     ok
19         sen-dakar     ok
20       alg-tindouf     ok
21        gha-kumasi     ok
22      lby-benghazi     ok
23        zmb-lusaka     ok
24        zaf-durban     ok
25         egy-cairo     ok
26      sdn-khartoum     ok
27       uga-kampala     ok
28    gbr-birmingham     ok
29        gbr-london     ok
30     nld-rotterdam     ok
31     rou-bucharest     ok
32        yem-dhamar     ok
33        sau-riyadh     ok
34    kwt-kuwaitcity     ok
35     rus-astrakhan     ok
36      are-abudhabi     ok
37     uzb-zarafshan     ok
38        ind-mumbai     ok
39          ind-tada     ok
40    ind-vijayawada     ok
41         bgd-dhaka     ok
42       chn-chengdu     ok
43        chn-zhuhai     ok
44     chn-guangzhou     ok
45         chn-wuhan     ok
46       chn-lujiang     ok
47      chn-yangzhou     ok
48   phl-angelescity     ok
49      chn-shanghai     ok
50        kor-sejong     ok
51     aus-melbourne     ok

In [12]:
summary

                city status
0      usa-brentwood     ok
1       usa-sandiego     ok
2          usa-boise     ok
3       usa-lasvegas     ok
4   usa-saltlakecity     ok
5   usa-permianbasin     ok
6     mex-mexicocity     ok
7    usa-bentonville     ok
8       usa-gonzales     ok
9        usa-atlanta     ok
10   usa-portstlucie     ok
11    pan-panamacity     ok
12       usa-raleigh     ok
13      jam-kingston     ok
14     usa-allentown     ok
15         per-cusco     ok
16        chl-calama     ok
17        bra-manaus     ok
18      bra-saopaulo     ok
19         sen-dakar     ok
20       alg-tindouf     ok
21        gha-kumasi     ok
22      lby-benghazi     ok
23        zmb-lusaka     ok
24        zaf-durban     ok
25         egy-cairo     ok
26      sdn-khartoum     ok
27       uga-kampala     ok
28    gbr-birmingham     ok
29        gbr-london     ok
30     nld-rotterdam     ok
31     rou-bucharest     ok
32        yem-dhamar     ok
33        sau-riyadh     ok
34    kwt-kuwaitcity     ok
35     rus-astrakhan     ok
36      are-abudhabi     ok
37     uzb-zarafshan     ok
38        ind-mumbai     ok
39          ind-tada     ok
40    ind-vijayawada     ok
41         bgd-dhaka     ok
42       chn-chengdu     ok
43        chn-zhuhai     ok
44     chn-guangzhou     ok
45         chn-wuhan     ok
46       chn-lujiang     ok
47      chn-yangzhou     ok
48   phl-angelescity     ok
49      chn-shanghai     ok
50        kor-sejong     ok
51     aus-melbourne     ok